### ISSUE TITLE
Error in panelView with a subset of units

### ISSUE THREAD

**Issue by aghosh19** [xuyiqing/panelView#1]
My data is unbalanced and by county and year. I was trying to see the extent of missing values by year with panelview command. As, there are many counties, I tried the panelview with a subset of units. I am getting this error:
```panelView(y ~ treatment, data = mydata,  index = c("county","year"), show.id = c(1:25))```

Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

Can you please let me know how to proceed from here? Thank you very much.

**Comment by xuyiqing** [comment]
we'll look into it asap. could you share with us a sample dataset to
replicate the error?

**Comment by aghosh19** [comment]
Thank you very much for getting back to me. This is a sample data that I am trying on:
```
df1 <- data.frame(county = c(01001, 01002, 02003, 04004, 08005, 01002, 02003, 04004, 08005, 01002, 01001),
                  name = c('Autaga', 'Fairfax', 'Orange', 'Loudoun', 'Arlington', 'Cook', 'Miami Dade', 'Nassau', 'Hudson', 'Pima', 'Harris'),
                  year = c(2008, 2007, 2006, 2005, 2008, 2005, 2009, 2006, 2007, 2008, 2009),
                  st = c('AL', 'VA', 'CA', 'VA','VA','IL','FL','NY','NJ','AZ', 'TX'),
                  y = c(0.02,0.4,0.6,0.7,0.8,0.6,0.4,0.8,0.01,0.02,0.5),
                  x = c(0, 1, 0, 0, 1, 0, 1, 1,0, 1, 1),
                  w = c(80,50,60,70,50,10,10,20,30,50,70))


panelView(y ~ x, data = df1,  index = c("county","year"), show.id = c(1:2))
```

**Comment by xuyiqing** [comment]
This bug has been fixed. Thanks for letting us know.
