### ISSUE TITLE
Can Date's be used as time indicator in the index?

### ISSUE THREAD

**Issue by jtorcasso** [xuyiqing/panelView#4]
My dataframe has a date in it that I'd like to use for the x-axis, so I use that as the time indicator. But I get an error. I can replicate with the following:

```R
test <- data.frame(
    month=as.Date(c('2020-01-01', '2020-02-01', '2020-01-01', '2020-02-01'), , format="%Y-%m-%d"),
    treat=c(0,0,1,1),
    revenue=c(10,12,9,15),
    idnum=c(1,1,2,2)
)
test$month_int <- as.integer(format(test$month, "%m"))
panelview(test, revenue ~ treat, index=c('idnum', 'month'), type="outcome")
```
```
Error in as.Date.numeric(value): 'origin' must be supplied
Traceback:

1. panelview(test, revenue ~ treat, index = c("idnum", "month"), 
 .     type = "outcome")
2. ave(data_aggregate[, 2], data_aggregate[, 1], FUN = length)
3. `split<-`(`*tmp*`, g, value = lapply(split(x, g), FUN))
4. `split<-.default`(`*tmp*`, g, value = lapply(split(x, g), FUN))
5. `[<-`(`*tmp*`, i, value = 2L)
6. `[<-.Date`(`*tmp*`, i, value = 2L)
7. as.Date(value)
8. as.Date.numeric(value)
9. stop("'origin' must be supplied")
```
When I use `month_int` instead, I don't get the error. I wish to use the actual dates for the x-axis. Is there a way to do this within panelview?

**Comment by xuyiqing** [comment]
I thought about this and decided not to allow Date because it introduces too many variable situations (and potentially gaps) in the plot. Thank you for the suggestion!

**Comment by jtorcasso** [comment]
Thanks for looking into this. In case anyone else comes across it, I ended up just making changes to plot after the fact. Though, I couldn't get `panelview` not to print out the initial plot as well, probably because the package explicitly prints the plot. Perhaps you could change the default behavior not to print the plot, and only to return it. 

```R
test <- data.frame(
    month=as.Date(c('2020-01-01', '2020-02-01', '2020-01-01', '2020-02-01'), , format="%Y-%m-%d"),
    treat=c(0,0,1,1),
    revenue=c(10,12,9,15),
    idnum=c(1,1,2,2)
)
test$month_int <- as.integer(format(test$month, "%m"))

# create function to map integer dates to actual dates, formatted as strings
tmap = test[!duplicated(test[,c('month_int', 'month')]), c('month_int', 'month')]
tmap = data.frame(month=tmap$month, row.names=tmap$month_int)
tlab <- function(x) {
    labs = tmap[sprintf('%s', x), 'month']
    labs = ifelse(is.na(labs), "", as.character(labs))
    return(labs)
}

p <- panelview(test, revenue ~ treat, index=c('idnum', 'month_int'), type="outcome")
p + scale_x_continuous(labels=tlab) + 
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1), 
          plot.margin = margin(10, 10, 20, 10))
```

**Comment by xuyiqing** [comment]
Thanks. We tried different things. Most users prefer print. If we change to print and return, the function will print it out twice. With the current setup, you still can save it as a ggplot2 object, like you just did. 

Thanks for the insights!
